### ISSUE TITLE
Creating a custom edge agent to schedule specific actions

### ISSUE THREAD

**Issue by Westlife1002** [Repast/repast.simphony#23]
I have a model with a lot of edges (links) between different sorts of other agents (objects). I would like to model these edges as agents where I could add attributes and schedule actions. It is helpful to see a simple example of how to do this job?

**Comment by jozik** [comment]
This question is now answered on Stack Overflow: https://stackoverflow.com/questions/57601451/repast-java-creating-a-custom-edge-agent-to-schedule-specific-actions

For future reference, please use Stack Overflow or the repast-interest mailing list for questions about Repast rather than this issues list.

**Comment by Westlife1002** [comment]
how to register in repast-interest mailing list?

**Comment by jozik** [comment]
Take a look at our support page: https://repast.github.io/support.html 
But feel free to continue asking questions on Stack Overflow.
