### ISSUE TITLE
Update JOGL to ver 2.4

### ISSUE THREAD

**Issue by etatara** [Repast/repast.simphony#31]
- [x] Update jogl jars
- [x] Update Repast vis code
- [x] Update demo models
- [x] Complete and verify testing

**Comment by ncollier** [comment]
Docking is not working correctly.

**Comment by ncollier** [comment]
Re.

On macOS rearranging displays results in:

java.lang.NullPointerException at saf.v3d.scene.VComposite.addChild(VComposite.java:46) at repast.simphony.visualizationOGL2D.SpatialWrapper.setChild(SpatialWrapper.java:80) at repast.simphony.visualizationOGL2D.SpatialWrapper.<init>(SpatialWrapper.java:34) at repast.simphony.visualizationOGL2D.StyledDisplayLayerOGL2D.createSpatial(StyledDisplayLayerOGL2D.java:146) at repast.simphony.visualizationOGL2D.StyledDisplayLayerOGL2D.processAdded(StyledDisplayLayerOGL2D.java:228) at repast.simphony.visualizationOGL2D.StyledDisplayLayerOGL2D.update(StyledDisplayLayerOGL2D.java:250)

This occurs because moving the dockable frame out of a container ultimately calls ShapeFactory2D.dispose(GLAutoDrawable drawable) which clears the texture cache, and if the child to be created is a texture, it can't be found so ShapeFactory2D.getNamedShape  returns null.

**Comment by ncollier** [comment]
Fixed in e8ddc72
