### ISSUE TITLE
How to debug repast

### ISSUE THREAD

**Issue by miaoxu9999** [Repast/repast.simphony#9]
Now I am learning how to use repast simphony. However, I find it is difficult for me to debug the repast by using eclipse. I would be appreciate it if who can teach me how to debug the repast simphony or send me some tutorials.

**Comment by jozik** [comment]
I'd recommend asking your questions on the repast-interest mailing list: https://sourceforge.net/projects/repast/lists/repast-interest
In the meantime, your question seems like more of a general Java question, rather than a Repast Simphony specific one. Here's a potentially helpful link: http://www.vogella.com/tutorials/EclipseDebugging/article.html
